-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 18:38:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Degree
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Degree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Degree` DEFAULT CHARACTER SET utf8 ;
USE `Degree` ;

-- -----------------------------------------------------
-- Table `Degree`.`College`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Degree`.`College` (
  `College_ID` INT NOT NULL,
  `clg_name` VARCHAR(100) NULL,
  PRIMARY KEY (`College_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Degree`.`Degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Degree`.`Degree` (
  `Degree_ID` INT NOT NULL,
  `Degree_Type` VARCHAR(100) NULL,
  `Degree_name` VARCHAR(100) NULL,
  `College_College_ID` INT NOT NULL,
  PRIMARY KEY (`Degree_ID`),
  INDEX `fk_Degree_College_idx` (`College_College_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Degree_College`
    FOREIGN KEY (`College_College_ID`)
    REFERENCES `Degree`.`College` (`College_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Degree`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Degree`.`Course` (
  `Course_ID` INT NOT NULL,
  `Course_name` VARCHAR(100) NULL,
  `Degree_Degree_ID` INT NOT NULL,
  PRIMARY KEY (`Course_ID`),
  INDEX `fk_Course_Degree1_idx` (`Degree_Degree_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Degree1`
    FOREIGN KEY (`Degree_Degree_ID`)
    REFERENCES `Degree`.`Degree` (`Degree_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Degree`.`College_Course_Degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Degree`.`College_Course_Degree` (
  `College_Course_Degree_ID` INT NOT NULL,
  `Fees` DOUBLE NULL,
  `Completion time` VARCHAR(20) NULL,
  `Description` VARCHAR(200) NULL,
  `College_College_ID` INT NOT NULL,
  `Degree_Degree_ID` INT NOT NULL,
  `Course_Course_ID` INT NOT NULL,
  PRIMARY KEY (`College_Course_Degree_ID`, `College_College_ID`, `Degree_Degree_ID`, `Course_Course_ID`),
  INDEX `fk_College_Course_Degree_College1_idx` (`College_College_ID` ASC) VISIBLE,
  INDEX `fk_College_Course_Degree_Degree1_idx` (`Degree_Degree_ID` ASC) VISIBLE,
  INDEX `fk_College_Course_Degree_Course1_idx` (`Course_Course_ID` ASC) VISIBLE,
  CONSTRAINT `fk_College_Course_Degree_College1`
    FOREIGN KEY (`College_College_ID`)
    REFERENCES `Degree`.`College` (`College_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_College_Course_Degree_Degree1`
    FOREIGN KEY (`Degree_Degree_ID`)
    REFERENCES `Degree`.`Degree` (`Degree_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_College_Course_Degree_Course1`
    FOREIGN KEY (`Course_Course_ID`)
    REFERENCES `Degree`.`Course` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;